### ISSUE TITLE
无法兼容新版本

### ISSUE THREAD

**Issue by LeonShannon** [paihuai00/JsonToArkTsModel#1]
![image](https://github.com/paihuai00/JsonToArkTsModel/assets/24221796/48254080-04a0-4e63-83b6-00b392977194)

DevEco Studio NEXT Developer Beta1
Build #DS-233.14475.28.36.503403
Build Version: 5.0.3.403, built on June 20, 2024
Runtime version: 17.0.10+1-b1087.17 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11.0
GC: G1 Young Generation, G1 Old Generation
Memory: 3928M
Cores: 16
Registry:
  idea.plugins.compatible.build=IC-233.14475.28

**Comment by paihuai00** [comment]
已修复，下载最新zip即可
